<?php
function e($v){return esc((string)$v);}
$filled=static fn($list)=>array_values(array_filter(is_array($list)?$list:[],static fn($x)=>is_array($x)?trim(implode('',array_map('strval',$x)))!=='':trim((string)$x)!==''));
$skills=$filled($data['skills']??[]);$edu=$filled($data['education']??[]);$ach=$filled($data['achievements']??[]);$refs=$filled($data['references']??[]);
$objective=trim((string)($data['objective']??''));
$photo=\App\Libraries\Photo::dataUri($resume['photo_path']??null);
$personal=['Date of Birth:'=>!empty($data['date_of_birth'])&&strtotime($data['date_of_birth'])?date('F j, Y',strtotime($data['date_of_birth'])):'','Citizenship:'=>$data['citizenship']??'','Sex:'=>$data['sex']??'','Civil Status:'=>$data['civil_status']??'','Height:'=>$data['height']??'','Weight:'=>$data['weight']??'','Languages/Dialect Spoken:'=>$data['languages']??''];
?>
<!doctype html><html><head><meta charset="utf-8"><style>@page{margin:0}*{box-sizing:border-box}body{margin:0;background:#eee;font-family:"Times New Roman",serif;color:#111}.page{background:white;margin:auto;padding:<?= $paperSize==='long'?'0.5in 1in':'8mm 24mm 8mm 25mm' ?>;font-size:12pt;line-height:1.15;min-height:<?= $paperSize==='long'?'13in':'297mm' ?>;width:<?= $paperSize==='long'?'8.5in':'210mm' ?>}.header{display:table;width:100%;border-bottom:1px solid #111;padding-bottom:8px;min-height:36mm}.headtext{display:table-cell;vertical-align:top}.photo{display:table-cell;width:37mm;text-align:right;vertical-align:top}.photo img{width:35mm;height:35mm;object-fit:cover;border:1px solid #111}.name{font-size:18pt;font-weight:bold;text-transform:uppercase}.section{margin-top:14px}.title{font-weight:bold;margin-bottom:3px}.title u{text-decoration:underline}.objective{text-align:justify;white-space:pre-line}.personal{border-collapse:collapse}.personal td{padding:0;vertical-align:top}.personal td:first-child{font-weight:bold;padding-right:14px;white-space:nowrap}.item{margin:2px 0}.edu{margin:0}.edu strong{display:block}.ach{margin:2px 0 2px 18px;font-weight:bold}.ref{display:table;width:100%;margin:4px 0;padding-left:18px}.refmain{display:table-cell}.refphone{display:table-cell;width:150px;font-weight:bold;text-align:left}.applicant{margin-top:30px}.applicant b{display:block;text-transform:uppercase;font-weight:normal}.muted{font-style:italic}</style></head><body><div class="page">
<div class="header"><div class="headtext"><div class="name"><?=e($data['full_name']??'')?></div><div><?=e($data['street']??'')?></div><div><?=e($data['location']??'')?></div><?php if(!empty($data['contact'])):?><div>Contact No.: <?=e($data['contact'])?></div><?php endif?><?php if(!empty($data['email'])):?><div>Email: <?=e($data['email'])?></div><?php endif?></div><div class="photo"><?php if($photo):?><img src="<?= $photo ?>" alt=""><?php endif?></div></div>
<?php if($objective!==''):?><div class="section"><div class="title"><u>OBJECTIVE</u>:</div><div class="objective"><?=e($objective)?></div></div><?php endif?>
<div class="section"><div class="title"><u>PERSONAL DATA</u>:</div><table class="personal"><?php foreach($personal as $label=>$value): if(trim((string)$value)==='') continue;?><tr><td><?=$label?></td><td><?=e($value)?></td></tr><?php endforeach?></table></div>
<?php if($skills):?><div class="section"><div class="title"><u>SKILLS &amp; QUALIFICATIONS</u>:</div><?php foreach($skills as $x):?><div class="item"><?=e($x)?></div><?php endforeach?></div><?php endif?>
<?php if($edu):?><div class="section"><div class="title"><u>EDUCATIONAL ATTAINMENT</u>:</div><?php foreach($edu as $x):?><div class="edu"><strong><?=e($x['level']??'')?></strong><?php foreach(['school','address','years'] as $k): if(trim((string)($x[$k]??''))!==''):?><div><?=e($x[$k])?></div><?php endif; endforeach?></div><?php endforeach?></div><?php endif?>
<?php if($ach):?><div class="section"><div class="title"><u>ACHIEVEMENT</u>:</div><?php foreach($ach as $x):?><div class="ach">• &nbsp;<?=e($x)?></div><?php endforeach?></div><?php endif?>
<?php if($refs):?><div class="section"><div class="title"><u>CHARACTER REFERENCES</u>:</div><?php foreach($refs as $x):?><div class="ref"><div class="refmain">• &nbsp;<b><?=e($x['name']??'')?></b><div style="padding-left:16px"><?=e($x['position']??'')?></div><div style="padding-left:16px"><?=e($x['organization']??'')?></div></div><div class="refphone"><?=e($x['contact']??'')?></div></div><?php endforeach?></div><?php endif?>
<div class="applicant"><b><?=e($data['full_name']??'')?></b><span class="muted">Applicant</span></div>
</div></body></html>
